# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - default
  # Changed which dataset to use
  - override dataset: EBNeRDsmall
  - override model: GLORY
  - _self_

optimizer:
  lr: 0.0002

num_epochs: 2
batch_size: 32            # dataloaders'batch_size = batch_size / gpu_num
accumulation_steps: 1     # final actual batch_size = batch_size * accumulation_steps
gpu_num: 1

# load or not
load_checkpoint: false
load_mark: base_small
train_mode: true
val_mode: true

model:
  # Set to true or false to use entity embeddings
  use_entity: true
  entity_neighbors: 10
  head_num: 20
  # Changed from 20 to 16 for entity embedding size
  head_dim: 16
  use_graph_type: 0
  directed: true
  num_neighbors: 8
  k_hops: 2
  

logger:
  exp_name: GLORY
  run_name: ${model.model_name}_${dataset.dataset_name}_${model.k_hops}-${model.num_neighbors}-${model.entity_neighbors}

ml_label: default

num_workers: 4
early_stop_patience: 5
reprocess: false
reprocess_neighbors: false
warmup_ratio: 0.1
log_steps: 1000

val_skip_epochs: 2
val_steps: 1000
